// DO NOT EDIT THIS FILE - IT IS AUTO GENERATED BY ROUTE-SAGE
const config = {
  "changelog": () => ({
    url: `/changelog`,
  }),
  "docs": () => ({
    url: `/docs`,
  }),
}

export default config;